# Generated by Django 3.1.13 on 2021-09-25 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('amount_invested', models.FloatField(blank=True, default=0, help_text='The total amount of deposit being invested by the investor in the given plan .', max_length=200, null=True, verbose_name='Amount Invested')),
                ('crypto_amount_invested', models.FloatField(blank=True, help_text='The total amount of deposit being invested by the investor in the given plan, amount invested in crypto currency .', max_length=200, null=True, verbose_name='Amount Invested In Crypto')),
                ('investment_start_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Investment start time begins the investment duration when the investor invested in the given plan.', null=True, verbose_name='Investment Start Time')),
                ('investment_end_time', models.DateTimeField(blank=True, help_text='Investment end time terminates the investment duration .', null=True, verbose_name='Investment End Time')),
                ('status', models.BooleanField(blank=True, default=True, help_text='The status that holds true or false if the plan is active or not.', null=True, verbose_name='Investment Status')),
                ('plan_name', models.ForeignKey(blank=True, help_text='The investment name given to the plan available to be invested on.', null=True, on_delete=django.db.models.deletion.PROTECT, to='investments.investment_plan', verbose_name='Investment Plan')),
                ('user', models.ForeignKey(blank=True, help_text='Investor whom the investment account history belong to.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
            ],
            options={
                'verbose_name': 'All Investment History',
                'verbose_name_plural': 'All Investment History',
                'ordering': ('-created_date',),
            },
        ),
    ]
