# Generated by Django 3.1.13 on 2021-09-25 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('transaction_type', models.CharField(blank=True, default='Deposited Funds', help_text='Transaction Type of the current investors deposit ', max_length=200, null=True, verbose_name='Transaction Type')),
                ('payment_gateway', models.CharField(blank=True, help_text='Payment Gateway of which the payment is been made through', max_length=200, null=True, verbose_name='Payment Gateway')),
                ('order_id', models.CharField(blank=True, help_text='Transaction order ID of the investors transaction', max_length=200, null=True, verbose_name='Transaction Order ID')),
                ('order', models.CharField(blank=True, default='Deposit', help_text='Order Type of the current investors deposit ', max_length=200, null=True, verbose_name='Order Type')),
                ('deposited_amount', models.FloatField(blank=True, default=0, help_text='Deposited Amount the investor current action', null=True, verbose_name='Deposit Amount')),
                ('crypto_deposit', models.FloatField(blank=True, default=0, help_text='Deposited Amount the investor current action', null=True, verbose_name='Deposit Amount In Crypto')),
                ('default_currency_id', models.CharField(blank=True, default='USD', help_text='The default currency of the investor. Currency will be sent against investors country of residence.', max_length=3, null=True, verbose_name='Default Currency ID')),
                ('available_balance', models.FloatField(blank=True, default=0, help_text='The investors available balance for the account', null=True, verbose_name='Available Balance')),
                ('crypto_available_balance', models.FloatField(blank=True, default=0, help_text='The investors available balance in crypto currency , converting the available balance to crypto currency', null=True, verbose_name='Crypto Balance')),
                ('payment_status', models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='unverified', help_text='The Payment status that holds the current state of the transaction', max_length=50, null=True, verbose_name='Payment Status')),
                ('reference_id', models.CharField(blank=True, help_text='Investors deposit Payment Reference ID, which is auto generated once the transaction is set to action', max_length=200, null=True, verbose_name='Payment Reference ID')),
                ('transaction_details', models.CharField(blank=True, help_text='investors Transaction details , hold the customized note for the current transaction. eg. Deposit Fund for Investment or Deposit Fund for available balance.', max_length=200, null=True, verbose_name='Transaction Details')),
                ('user', models.ForeignKey(blank=True, help_text='The User associated with this deposit history', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'All Deposit Fund',
                'verbose_name_plural': 'All Deposit Fund',
                'ordering': ('-created_date',),
            },
        ),
    ]
