# Generated by Django 3.1.13 on 2021-12-04 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ('-created_date',), 'verbose_name': 'All Deposited Fund', 'verbose_name_plural': 'All Deposited Fund'},
        ),
    ]
