# Generated by Django 3.1.13 on 2021-09-22 20:58

from django.db import migrations, models
import investodd.users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Register Investor', 'verbose_name_plural': 'Register Investor'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', investodd.users.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='The first nammes of the investor.', max_length=50, null=True, verbose_name='First names'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='The last nammes of the investor.', max_length=50, null=True, verbose_name='Last names'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/default.png', help_text='The profile image of the investor.', null=True, upload_to='profile_image/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='The email address of the investor.', max_length=150, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the investor.', primary_key=True, serialize=False),
        ),
    ]
