# Generated by Django 3.1.13 on 2021-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_balance',
            field=models.IntegerField(blank=True, default=0, help_text='The investors available balance for the account', null=True, verbose_name='Available Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='The date of birth of the customer.', null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency_id',
            field=models.CharField(blank=True, default='USD', help_text='The default currency of the investor. Currency will be sent against investors country of residence.', max_length=3, null=True, verbose_name='Default Currency ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(default=False, help_text='Flag to determine if a cutomer have completed KYC verification', verbose_name='KYC complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer completed KYC verifiction process.', null=True, verbose_name='KYC complete date'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('action_required', 'Action_required'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected/Refused')], default='Unverified', help_text='The .', max_length=15, null=True, verbose_name='KYC status'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(blank=True, help_text='Flag to determine if customer has submitted a KYC verification.', null=True, verbose_name='KYC submitted'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_bonus',
            field=models.IntegerField(blank=True, default=0, help_text='The investors referral bonus balance for the account', null=True, verbose_name='Referral Bonus'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_balance',
            field=models.IntegerField(blank=True, default=0, help_text='The investors withdrable balance for the account', null=True, verbose_name='Withdrawal Balance'),
        ),
    ]
