# Generated by Django 3.1.13 on 2021-09-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210923_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crypto_balance',
            field=models.IntegerField(blank=True, default=0, help_text='The investors available balance in crypto currency , converting the available balance to crypto currency', null=True, verbose_name='Crypto Balance'),
        ),
    ]
