# Generated by Django 3.1.13 on 2021-09-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_crypto_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='crypto_balance',
            new_name='crypto_available_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='crypto_referral_bonus',
            field=models.IntegerField(blank=True, default=0, help_text='The investors withdrable balance in crypto converting the withdrawable balance to crypto currency', null=True, verbose_name='Crypto Referral Balance'),
        ),
        migrations.AddField(
            model_name='user',
            name='crypto_withdrawal_balance',
            field=models.IntegerField(blank=True, default=0, help_text='The investors withdrable balance in crypto converting the withdrawable balance to crypto currency', null=True, verbose_name='Crypto Withdrawal Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='available_balance',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The investors available balance for the account', null=True, verbose_name='Available Balance'),
        ),
    ]
