# Generated by Django 3.1.13 on 2021-09-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210924_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crypto_available_balance',
            field=models.FloatField(blank=True, default=0, help_text='The investors available balance in crypto currency , converting the available balance to crypto currency', null=True, verbose_name='Crypto Balance'),
        ),
    ]
