# Generated by Django 3.1.13 on 2021-09-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210924_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_balance',
            field=models.FloatField(blank=True, default=0, help_text='The investors available balance for the account', null=True, verbose_name='Available Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='crypto_referral_bonus',
            field=models.FloatField(blank=True, default=0, help_text='The investors withdrable balance in crypto converting the withdrawable balance to crypto currency', null=True, verbose_name='Crypto Referral Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='crypto_withdrawal_balance',
            field=models.FloatField(blank=True, default=0, help_text='The investors withdrable balance in crypto converting the withdrawable balance to crypto currency', null=True, verbose_name='Crypto Withdrawal Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_bonus',
            field=models.FloatField(blank=True, default=0, help_text='The investors referral bonus balance for the account', null=True, verbose_name='Referral Bonus'),
        ),
        migrations.AlterField(
            model_name='user',
            name='withdrawal_balance',
            field=models.FloatField(blank=True, default=0, help_text='The investors withdrable balance for the account', null=True, verbose_name='Withdrawal Balance'),
        ),
    ]
