# Generated by Django 3.1.13 on 2021-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210924_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='crypto_referral_bonus',
            field=models.FloatField(blank=True, default=0, help_text='The investors withdrable balance in crypto converting the referral balance to crypto currency', null=True, verbose_name='Crypto Referral Balance'),
        ),
    ]
