# Generated by Django 3.1.13 on 2021-09-24 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210924_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of an object.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the record was created.', max_length=20, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Modified date when the record was created.', max_length=20, verbose_name='Modified Date')),
                ('hostname', models.CharField(blank=True, help_text='The Host Name of the logged in user system', max_length=355, null=True, verbose_name='Host Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, help_text=' The system IP address to current login user', null=True, verbose_name='System IP Address')),
                ('user', models.ForeignKey(help_text='The user for whom account belongs to', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User Profile')),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activity',
            },
        ),
    ]
