# Generated by Django 3.1.13 on 2021-09-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ('-created_date',), 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activity'},
        ),
    ]
