# Generated by Django 3.1.13 on 2021-09-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210925_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'All Registered Investors', 'verbose_name_plural': 'All Registered Investors'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ('-created_date',), 'verbose_name': 'All Users Activity', 'verbose_name_plural': 'All Users Activity'},
        ),
    ]
